targets:
  $default:
    builders:
      hive|hive:
        enabled: false
        generate_for:
          - '**/models/**.dart'
        options:
          include_if_null: false
      mockito|mockito:
        enabled: true
        options:
          include_if_null: false