name: lolwiki
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #API keys security
  flutter_dotenv: ^5.0.2

  #data persistence
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  #state management
  provider: ^6.0.2

  #localization
  easy_localization: ^3.0.0

  #API calls
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    