name: leaguechamps
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #Data persistence
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0

  #State management and DI
  provider: ^6.0.2

  #Localization
  easy_localization: ^3.0.0

  #API calls
  http: ^0.13.4

  #Testing
  mockito: ^5.1.0

  #Logger
  easy_logger: ^0.0.2

  #Connection checking
  connectivity_plus: ^2.3.0

  #Toast messages
  fluttertoast: ^8.0.9

  #Animating widgets
  flutter_staggered_animations: ^1.0.0
  animations: ^2.0.2
  
  #Loading states
  shimmer: ^2.0.0

  #For Privacy Policy
  webview_flutter: ^3.0.4

  #Object comparison
  equatable: ^2.0.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
    
  #Testing Hive
  hive_test: ^1.0.1

  #Code generation
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

  #App Logo
  icons_launcher: ^1.1.8

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/champ_classes/
    - assets/images/
    