name: lolwiki
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #API key security
  flutter_dotenv: ^5.0.2

  #Data persistence
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0

  #State management
  provider: ^6.0.2

  #Localization
  easy_localization: ^3.0.0

  #API calls
  http: ^0.13.4

  #Testing
  mockito: ^5.1.0

  #Logger
  easy_logger: ^0.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  #Code generation
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/champ_classes/
    